import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/index'
import Footer from '@/components/Footer/index'

import { NextAuthProvider } from './NextAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <NextAuthProvider>
          <Navbar />
            {children}
            <Footer />
          </NextAuthProvider>
      </body>
    </html>
  )
}
